git.sr.ht:
  enabled: true

image: nixos/unstable
tasks:
- test: |
    # FIXME use a flake or at lesat a shell with an overlay or something
    nix-env -iA nixos.cargo nixos.gcc
    cd taskwarrior-hooks/
    cargo test
